# Generated by Django 5.0.4 on 2024-07-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_contact_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
