# Generated by Django 5.0.4 on 2024-05-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_resumes_processed', models.IntegerField(default=0)),
                ('total_screening_time', models.DurationField(default=0)),
            ],
        ),
    ]
