# Generated by Django 5.0.4 on 2024-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_alter_screeningmetrics_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningmetrics',
            name='for_role',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
