# Generated by Django 5.0.4 on 2024-07-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_group',
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
