# Generated by Django 5.0.4 on 2024-07-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_remove_employee_employee_group_employee_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
