# Generated by Django 5.0.4 on 2024-07-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.jobopening')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.stage')),
            ],
        ),
    ]
