# Generated by Django 5.0.4 on 2024-07-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatestage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
    ]
