# Generated by Django 5.0.4 on 2024-09-20 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidate_company'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('interviewer', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=256)),
                ('interview_type', models.CharField(choices=[('face to face', 'Face to face'), ('virtual', 'Virtual'), ('telephonic', 'Telephonic')], max_length=100)),
                ('interview_url', models.URLField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
