# Generated by Django 5.0.4 on 2024-09-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidate_company'),
        ('dashboard', '0003_event_company_alter_event_description'),
        ('manager', '0003_jobopening_education_jobopening_max_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='for_designation',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='manager.jobopening'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='event',
            name='interview_type',
            field=models.CharField(choices=[('facetoface', 'Face to face'), ('virtual', 'Virtual'), ('telephonic', 'Telephonic')], max_length=100),
        ),
    ]
