# Generated by Django 5.0.4 on 2024-09-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_event_for_designation_alter_event_candidate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='for_designation',
            new_name='designation',
        ),
    ]
