# Generated by Django 5.1 on 2025-03-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_event_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
