# Generated by Django 5.1 on 2025-08-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_alter_candidate_job_openings_and_more'),
        ('dashboard', '0007_alter_event_interview_url_alter_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_opening_id', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'unique_together': {('candidate', 'job_opening_id')},
            },
        ),
    ]
