# Generated by Django 5.1 on 2026-02-05 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_interviewinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestage',
            name='moved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
