# Generated by Django 5.1 on 2026-02-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_candidatestage_moved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatestage',
            name='moved_at',
        ),
    ]
