# Generated by Django 5.1 on 2026-02-05 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_candidatestage_moved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestage',
            name='moved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
