# Generated by Django 5.0.4 on 2024-05-03 08:59

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_screeningmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningmetrics',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='screeningmetrics',
            name='total_screening_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
