# Generated by Django 5.0.4 on 2024-05-03 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_screeningmetrics_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningmetrics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
