# Generated by Django 5.0.4 on 2024-07-17 06:13

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='website',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='candidate',
            name='blog',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_ctc_ih',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_ctc_ih',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='github',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portofolio',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='doc',
            field=models.DateField(blank=True, default=candidate.models.today),
        ),
    ]
