# Generated by Django 5.0.4 on 2024-08-30 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='created_by',
        ),
        migrations.AddField(
            model_name='candidate',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='text_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='upload_resume',
            field=models.FileField(null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'], message='Select pdf, docx or doc files only')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
