# Generated by Django 5.0.4 on 2024-09-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_remove_candidate_created_by_candidate_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='doc',
        ),
    ]
