# Generated by Django 5.0.4 on 2024-07-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_rename_website_candidate_linkedin_candidate_blog_and_more'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='portofolio',
            new_name='portfolio',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_openings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.jobopening'),
        ),
    ]
