# Generated by Django 5.0.4 on 2024-07-20 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_rename_portofolio_candidate_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
