# Generated by Django 5.0.4 on 2024-09-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_resumeanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='candidate.candidate'),
        ),
    ]
