# Generated by Django 5.0.4 on 2024-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_ctc',
            field=models.FloatField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_ctc_ih',
            field=models.FloatField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_ctc',
            field=models.FloatField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_ctc_ih',
            field=models.FloatField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='notice_period',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='offer_in_hand',
            field=models.FloatField(blank=True, default=0, max_length=255),
        ),
    ]
