# Generated by Django 5.0.4 on 2024-09-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_alter_resumeanalysis_candidate'),
        ('manager', '0003_jobopening_education_jobopening_max_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_opening',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.jobopening'),
        ),
    ]
