# Generated by Django 5.0.4 on 2024-07-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_alter_candidate_current_ctc_and_more'),
        ('manager', '0003_jobopening_job_mode_jobopening_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job_openings',
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_openings',
            field=models.ManyToManyField(blank=True, null=True, to='manager.jobopening'),
        ),
    ]
