# Generated by Django 5.0.4 on 2024-10-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
