# Generated by Django 5.0.4 on 2024-10-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_candidate_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='response_text',
            field=models.JSONField(null=True),
        ),
    ]
