# Generated by Django 5.1 on 2025-03-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_alter_resumeanalysis_response_text'),
        ('manager', '0007_remove_jobopening_education_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='job_openings',
            field=models.ManyToManyField(blank=True, null=True, to='manager.jobopening'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
