# Generated by Django 5.1 on 2026-02-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_alter_candidate_job_openings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='share_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
