# Generated by Django 5.2.10 on 2026-02-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_candidate_preferred_location_candidate_share_date'),
        ('manager', '0019_remove_client_payment_id_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='manager.client'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
