# Generated by Django 5.2.10 on 2026-05-26 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_candidate_client_candidate_college'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='Size of the file in bytes'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_candidates', to=settings.AUTH_USER_MODEL),
        ),
    ]
