# Generated by Django 5.0.4 on 2024-07-10 05:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=400)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('contact', models.CharField(blank=True, max_length=12)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('openings', models.PositiveIntegerField(validators=[manager.models.exempt_zero])),
                ('requiredskills', models.CharField(blank=True, max_length=1000)),
                ('jobdescription', models.FileField(blank=True, upload_to='jd/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'txt'], message='Select pdf, docx, doc or txt files only')])),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('jd_content', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, choices=[('file', 'File'), ('text', 'Text')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('assignemployee', models.ManyToManyField(to='users.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.organization')),
            ],
        ),
    ]
