# Generated by Django 5.0.4 on 2024-07-04 08:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('openings', models.PositiveIntegerField(validators=[manager.models.exempt_zero])),
                ('requiredskills', models.CharField(blank=True, max_length=1000)),
                ('jobdescription', models.FileField(blank=True, upload_to='jd/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'txt'], message='Select pdf, docx, doc or txt files only')])),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('jd_content', models.TextField(blank=True)),
                ('assignemployee', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, choices=[('file', 'File'), ('text', 'Text')], max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.organization')),
            ],
        ),
    ]
