# Generated by Django 5.0.4 on 2024-07-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='budget',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
