# Generated by Django 5.0.4 on 2024-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_jobopening_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='job_mode',
            field=models.CharField(blank=True, choices=[('Office', 'Office'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Contractual', 'Contractual'), ('Permanent', 'Permanent')], max_length=50),
        ),
    ]
