# Generated by Django 5.0.4 on 2024-09-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_jobopening_client_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='education',
            field=models.CharField(blank=True, default='graduate', max_length=255),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='max_experience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='min_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
