# Generated by Django 5.0.4 on 2024-07-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_jobopening'),
        ('users', '0003_alter_employee_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='assignemployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
    ]
