# Generated by Django 5.0.4 on 2024-08-02 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_jobopening_job_mode_jobopening_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(blank=True, upload_to='applications/')),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.jobopening')),
            ],
        ),
    ]
