# Generated by Django 5.0.4 on 2024-09-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_jobopening_education_jobopening_max_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='expires',
            field=models.IntegerField(default=21),
        ),
    ]
