# Generated by Django 5.0.4 on 2024-07-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_jobopening_assignemployee'),
        ('users', '0003_alter_employee_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='assignemployee',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='assignemployee',
            field=models.ManyToManyField(null=True, to='users.employee'),
        ),
    ]
