# Generated by Django 5.0.4 on 2024-08-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='requiredskills',
            field=models.TextField(blank=True),
        ),
    ]
