# Generated by Django 5.0.4 on 2024-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_jobopening_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='education_criteria',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='experience_criteria',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='skills_criteria',
            field=models.IntegerField(default=50),
        ),
    ]
