# Generated by Django 5.0.4 on 2024-08-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_jobopening_requiredskills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobopening',
            options={'ordering': ['-updated_on']},
        ),
    ]
