# Generated by Django 5.0.4 on 2024-10-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_jobopening_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='education_criteria',
        ),
        migrations.RemoveField(
            model_name='jobopening',
            name='experience_criteria',
        ),
    ]
