# Generated by Django 5.1 on 2025-06-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_jobopening_education_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
