# Generated by Django 5.1 on 2026-02-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_jobopening_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
