# Generated by Django 5.1 on 2026-02-08 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_client_created_by_client_description_client_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.AddField(
            model_name='client',
            name='agreement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='client_agreements/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='client',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='client',
            name='client_document',
            field=models.FileField(blank=True, null=True, upload_to='client_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='client',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GSTIN', max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='multiple_emails',
            field=models.TextField(blank=True, help_text='Comma-separated multiple email IDs'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_id',
            field=models.CharField(blank=True, help_text='UPI / Bank / Payment Reference ID', max_length=150),
        ),
    ]
