# Generated by Django 5.1 on 2026-02-08 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_remove_client_created_at_remove_client_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='agreement_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agreement_file',
        ),
        migrations.RemoveField(
            model_name='client',
            name='alternate_contact',
        ),
        migrations.RemoveField(
            model_name='client',
            name='alternate_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_document',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='client',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='multiple_emails',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
