# Generated by Django 5.1 on 2026-02-09 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_remove_client_agreement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.AddField(
            model_name='client',
            name='Emails',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AddField(
            model_name='client',
            name='agreement_upload',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
        migrations.AddField(
            model_name='client',
            name='alternative_contact',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='client',
            name='alternative_email',
            field=models.TextField(blank=True, help_text='Comma-separated emails'),
        ),
        migrations.AddField(
            model_name='client',
            name='document_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='client',
            name='gst_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
