# Generated by Django 5.1 on 2026-02-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_remove_client_created_at_remove_client_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Emails',
        ),
        migrations.AlterField(
            model_name='client',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_emails', to='manager.client')),
            ],
        ),
    ]
