# Generated by Django 5.1 on 2026-02-09 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_remove_client_emails_alter_client_alternative_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClientEmail',
        ),
    ]
