# Generated by Django 5.1 on 2026-02-09 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_client_created_by_delete_clientemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_emails', to='manager.client')),
            ],
        ),
    ]
