# Generated by Django 5.2.10 on 2026-02-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_clientemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
