# Generated by Django 5.2.10 on 2026-02-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_jobopening_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
