# Generated by Django 5.2.10 on 2026-02-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_remove_client_payment_id_client_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commercials_decided',
            field=models.TextField(blank=True, null=True),
        ),
    ]
