# Generated by Django 5.2.10 on 2026-02-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
